# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'
target 'Nanna_Shaale' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for Nanna_Shaale

  target 'Nanna_Shaale-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Nanna_ShaaleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Nanna_Shaale-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Nanna_Shaale-tvOS

  target 'Nanna_Shaale-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
